# Copyright (c) 2023, Tom M. Ragonneau
name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    name: Compile LaTeX documents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Generate the PDF document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: op23.tex
          args: -file-line-error -halt-on-error -interaction=nonstopmode
          extra_fonts: |
            ./fonts/fira-mono/*.otf
            ./fonts/fira-sans/*.otf
          pre_compile: tlmgr update --self && tlmgr update --all

      - name: Rename the PDF document
        run: bash .github/actions/build/rename.sh

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: "*.pdf"
          if-no-files-found: error
