# Copyright (c) 2023, Tom M. Ragonneau
name: spelling

on:
  push:
  pull_request_target:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  spelling:
    name: Check spelling
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    permissions:
      contents: read
      pull-requests: read
      actions: read
      security-events: write
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If only_check_changed_files is true, set cancel-in-progress to false
      cancel-in-progress: true

    steps:
      - name: Check spelling
        id: spelling
        uses: check-spelling/check-spelling@main
        with:
          suppress_push_for_open_pull_request: 1
          checkout: true
          check_file_names: 1
          spell_check_this: check-spelling/spell-check-this@prerelease
          post_comment: 0
          use_magic_file: 1
          experimental_apply_changes_via_bot: 1
          use_sarif: 1
          extra_dictionary_limit: 10

  comment-push:
    name: Report (push)
    runs-on: ubuntu-latest
    needs: spelling
    if: (success() || failure()) && needs.spelling.outputs.followup && github.event_name == 'push'
    permissions:
      contents: write

    steps:
      - name: Comment
        uses: check-spelling/check-spelling@main
        with:
          checkout: true
          spell_check_this: check-spelling/spell-check-this@prerelease
          task: ${{ needs.spelling.outputs.followup }}

  comment-pr:
    name: Report (PR)
    runs-on: ubuntu-latest
    needs: spelling
    if: (success() || failure()) && needs.spelling.outputs.followup && contains(github.event_name, 'pull_request')
    permissions:
      pull-requests: write

    steps:
      - name: Comment
        uses: check-spelling/check-spelling@main
        with:
          checkout: true
          spell_check_this: check-spelling/spell-check-this@prerelease
          task: ${{ needs.spelling.outputs.followup }}
          experimental_apply_changes_via_bot: 1

  update:
    name: Update PR
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@check-spelling-bot apply') }}
    permissions:
      contents: write
      pull-requests: write
      actions: read
    concurrency:
      group: spelling-update-${{ github.event.issue.number }}
      cancel-in-progress: false

    steps:
      - name: Apply spelling updates
        uses: check-spelling/check-spelling@main
        with:
          experimental_apply_changes_via_bot: 1
          checkout: true
          ssh_key: "${{ secrets.CHECK_SPELLING }}"
